conda_environment: "workflow/envs/nextstrain.yaml"

genesforglycosylation: ["G", "F"]
builds_to_run: ["genome"]
resolutions_to_run: ["all-time"]

# Always include all strains from Norway
include:
  - "country == 'Norway'"

exclude: "config/outliers.txt"
description: "config/description.md"

strain_id_field: "accession"
display_strain_field: "strain"

subtypes: ['a','b']

filter:
  # Grouping by year and country ensures representative sampling for non-Norwegian sequences
  group_by: "year country"
  
  # Minimum coverage thresholds
  min_coverage:
    genome: 0.3
    G: 0.3
    F: 0.3

  # Minimum length thresholds
  min_length:
    genome: 10000
    G: 600
    F: 1200

  # Date ranges for resolutions
  resolutions:
    all-time:
      min_date: 1900
      max_date: 2100  
    6y:
      min_date: 2018
      max_date: 2025  
      background_min_date: 100Y
    3y:
      min_date: 2022
      max_date: 2025
      background_min_date: 100Y

  subsample_max_sequences:
    genome: 3000
    G: 3000
    F: 3000

files:
  color_schemes: "config/colors.tsv"
  auspice_config: "config/auspice_config.json"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "country"

nextclade_attributes:
  a:
    name: "RSV-A NextClade using real-time tree"
    reference_name: "hRSV/A/England/397/2017"
    accession: "EPI_ISL_412866"
  b:
    name: "RSV-B NextClade using real-time tree"
    reference_name: "hRSV/B/Australia/VIC-RCH056/2019"
    accession: "EPI_ISL_1653999"
