include: "../rules/config.smk"

include: "../rules/main.smk"

include: "../rules/genome.smk"

rule _all:
    input:
        expand("auspice/{subtype}_{segment}.json",
               subtype="h5n1",
               segment=["genome", "pb2", "pb1", "pa", "ha", "np", "na", "mp", "ns"])
