name: Publish Docker image (hcv_illumina)

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./hcv_illumina
          file: ./hcv_illumina/Dockerfile
          push: true
          tags: |
            ghcr.io/jonbra/ngs_scripts/hcv_illumina:${{ env.TAG }}
